import { KRICard, Alert } from "@/types/risk";

export const kriCards: KRICard[] = [
  {
    id: "npl",
    title: "NPL 비율",
    value: 1.82,
    unit: "%",
    displayValue: "1.82%",
    severity: "caution",
    trend: "up",
    trendValue: 0.12,
    threshold: { caution: 1.5, warning: 2.0, danger: 3.0 },
    description: "고정이하여신 비율",
    category: "credit",
  },
  {
    id: "bis",
    title: "BIS 자기자본비율",
    value: 15.3,
    unit: "%",
    displayValue: "15.3%",
    severity: "normal",
    trend: "down",
    trendValue: -0.2,
    threshold: { caution: 13.0, warning: 10.5, danger: 8.0 },
    description: "총자본 / 위험가중자산",
    category: "credit",
  },
  {
    id: "var",
    title: "VaR (일)",
    value: 1250,
    unit: "억원",
    displayValue: "1,250억",
    severity: "normal",
    trend: "up",
    trendValue: 85,
    threshold: { caution: 1200, warning: 1400, danger: 1600 },
    description: "99% 신뢰수준 일일 VaR",
    category: "market",
  },
  {
    id: "lcr",
    title: "LCR",
    value: 142.3,
    unit: "%",
    displayValue: "142.3%",
    severity: "normal",
    trend: "down",
    trendValue: -3.1,
    threshold: { caution: 120, warning: 110, danger: 100 },
    description: "유동성커버리지비율",
    category: "liquidity",
  },
  {
    id: "nsfr",
    title: "NSFR",
    value: 118.7,
    unit: "%",
    displayValue: "118.7%",
    severity: "caution",
    trend: "down",
    trendValue: -1.8,
    threshold: { caution: 115, warning: 110, danger: 100 },
    description: "순안정자금조달비율",
    category: "liquidity",
  },
  {
    id: "cet1",
    title: "CET1 비율",
    value: 13.1,
    unit: "%",
    displayValue: "13.1%",
    severity: "normal",
    trend: "stable",
    trendValue: 0.05,
    threshold: { caution: 11.5, warning: 9.5, danger: 7.0 },
    description: "보통주자본비율",
    category: "credit",
  },
  {
    id: "leverage",
    title: "레버리지비율",
    value: 5.8,
    unit: "%",
    displayValue: "5.8%",
    severity: "normal",
    trend: "stable",
    trendValue: 0.1,
    threshold: { caution: 4.0, warning: 3.5, danger: 3.0 },
    description: "기본자본 / 총익스포저",
    category: "credit",
  },
  {
    id: "concentration",
    title: "대형차주 집중도",
    value: 38.2,
    unit: "%",
    displayValue: "38.2%",
    severity: "warning",
    trend: "up",
    trendValue: 2.3,
    threshold: { caution: 30, warning: 35, danger: 45 },
    description: "상위 20개 차주 익스포저 비중",
    category: "credit",
  },
];

export const alerts: Alert[] = [
  {
    id: "alert-1",
    severity: "warning",
    title: "NPL 비율 주의 임계값 초과",
    message: "NPL 비율이 1.82%로 주의 임계값(1.5%)을 초과하였습니다. 추가 모니터링이 필요합니다.",
    timestamp: "2026-02-26T09:15:00+09:00",
    category: "credit",
    isRead: false,
  },
  {
    id: "alert-2",
    severity: "warning",
    title: "대형차주 집중도 경보 수준 근접",
    message: "대형차주 집중도 38.2%가 경보 임계값(45%)에 근접하고 있습니다.",
    timestamp: "2026-02-26T08:30:00+09:00",
    category: "credit",
    isRead: false,
  },
  {
    id: "alert-3",
    severity: "caution",
    title: "NSFR 비율 하락 추세",
    message: "NSFR이 118.7%로 전월 대비 1.8%p 하락하여 모니터링이 필요합니다.",
    timestamp: "2026-02-26T07:00:00+09:00",
    category: "liquidity",
    isRead: true,
  },
  {
    id: "alert-4",
    severity: "caution",
    title: "VaR 한도 근접",
    message: "일일 VaR 1,250억원이 한도(1,500억원)의 83.3%에 달했습니다.",
    timestamp: "2026-02-25T17:45:00+09:00",
    category: "market",
    isRead: true,
  },
];
