"""
create_td_irriskmr.py - TD_IRRISKMR 테이블 생성
실행: python db/create_td_irriskmr.py
"""
import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

DDL = """
DROP TABLE IF EXISTS td_irriskmr;
CREATE TABLE td_irriskmr (
    std_date                    CHAR(8)         NOT NULL,
    org_code                    VARCHAR(6)      NOT NULL,
    con_sep_clcd                VARCHAR(1)      NOT NULL,
    port_no                     NUMERIC(20,0)   NOT NULL,
    ncr_stress_no               NUMERIC(20,0)   NOT NULL,
    bo_item_code                VARCHAR(100)    NOT NULL,
    con_sep_clnm                VARCHAR(200),
    bo_dept_cd01                VARCHAR(20),
    bo_dept_nm01                VARCHAR(100),
    bo_dept_cd02                VARCHAR(20),
    bo_dept_nm02                VARCHAR(100),
    bo_dept_cd03                VARCHAR(20),
    bo_dept_nm03                VARCHAR(100),
    bo_dept_cd04                VARCHAR(20),
    bo_dept_nm04                VARCHAR(100),
    bo_dept_cd05                VARCHAR(20),
    bo_dept_nm05                VARCHAR(100),
    biz_area_cd                 VARCHAR(4),
    biz_area_nm                 VARCHAR(100),
    item_code                   VARCHAR(100),
    item_name                   VARCHAR(200),
    fund_code                   VARCHAR(80),
    fund_name                   VARCHAR(100),
    cust_fund_code              VARCHAR(100),
    cust_fund_name              VARCHAR(100),
    bo_good_cd01                VARCHAR(20),
    bo_good_nm01                VARCHAR(100),
    bo_good_cd02                VARCHAR(20),
    bo_good_nm02                VARCHAR(100),
    bo_good_cd03                VARCHAR(20),
    bo_good_nm03                VARCHAR(100),
    good_grp1                   VARCHAR(6),
    good_grp_nm1                VARCHAR(100),
    good_grp2                   VARCHAR(6),
    good_grp_nm2                VARCHAR(100),
    good_grp3                   VARCHAR(6),
    good_grp_nm3                VARCHAR(100),
    bo_acct_cd01                VARCHAR(20),
    bo_acct_nm01                VARCHAR(100),
    acct_oper_type              VARCHAR(10),
    acct_oper_name              VARCHAR(100),
    sub_item_code               VARCHAR(100),
    sub_item_name               VARCHAR(200),
    underlying_id               VARCHAR(50),
    underlying_name             VARCHAR(100),
    underlying_grp              VARCHAR(10),
    underlying_grp_name         VARCHAR(100),
    deal_type                   CHAR(1),
    deal_name                   VARCHAR(100),
    trade_date                  CHAR(8),
    due_date                    CHAR(8),
    srvl_dcnt                   NUMERIC(20,15),
    srvl_mcnt                   NUMERIC(20,15),
    currency_code               VARCHAR(10),
    fx_rate                     NUMERIC(20,15),
    cpty_code                   VARCHAR(50),
    cpty_name                   VARCHAR(500),
    cpty_gbn                    VARCHAR(2),
    cpty_gbn_nm                 VARCHAR(100),
    cover_yn                    CHAR(1),
    sp_rlt_yn                   VARCHAR(1),
    firm_grp_id                 VARCHAR(50),
    firm_grp_name               VARCHAR(500),
    cpty_crdt_eval_grad         VARCHAR(10),
    cpty_crdt_eval_grad_nm      VARCHAR(10),
    sec_crdt_eval_grad          VARCHAR(10),
    sec_crdt_eval_grad_nm       VARCHAR(10),
    cds_ref_crdt_eval_grad      VARCHAR(10),
    cds_ref_crdt_eval_grad_nm   VARCHAR(10),
    ncr_grad_cd                 VARCHAR(10),
    ncr_grad_cd_nm              VARCHAR(10),
    face_unit                   NUMERIC(30,13),
    face_amt                    NUMERIC(30,13),
    market_price                NUMERIC(30,13),
    book_amt                    NUMERIC(30,13),
    notional_amt                NUMERIC(30,13),
    market_amt                  NUMERIC(30,13),
    eval_pl_amt                 NUMERIC(30,13),
    posi_amt                    NUMERIC(30,13),
    fx_risk_posi_amt            NUMERIC(30,13),
    delta_posi_amt              NUMERIC(30,13),
    gamma_posi_amt              NUMERIC(30,13),
    vega_posi_amt               NUMERIC(30,13),
    bef_std_amt                 NUMERIC(30,13),
    std_amt                     NUMERIC(30,13),
    inter_yn                    CHAR(1),
    etf_yn                      VARCHAR(1),
    lvrg_rate                   NUMERIC(20,15),
    ncr_st_gbn                  VARCHAR(2),
    ncr_st_gbn_nm               VARCHAR(100),
    nat_cd                      VARCHAR(3),
    nat_nm                      VARCHAR(100),
    qlfc_mkt_cd                 VARCHAR(5),
    qlfc_mkt_nm                 VARCHAR(500),
    mkt_ind_cd                  VARCHAR(100),
    mkt_ind_nm                  VARCHAR(500),
    bskt_mkt_tot_amt            NUMERIC(30,13),
    bskt_beta                   NUMERIC(20,15),
    bskt_r2                     NUMERIC(20,15),
    float_sfcc_yn               VARCHAR(1),
    dvrsf_sfcc_yn               VARCHAR(1),
    buy_item_gbn                VARCHAR(2),
    buy_item_code               VARCHAR(15),
    buy_item_name               VARCHAR(100),
    buy_position_amt            NUMERIC(30,13),
    sel_item_gbn                VARCHAR(2),
    sel_item_code               VARCHAR(15),
    sel_item_name               VARCHAR(100),
    sel_position_amt            NUMERIC(30,13),
    mprf_tr_posi_amt            NUMERIC(30,13),
    ind_mkt_tot_amt             NUMERIC(30,13),
    item_pos_qty                NUMERIC(20,0),
    list_st_qty                 NUMERIC(20,0),
    item_list_st_qty            NUMERIC(20,0),
    st_change_ratio             NUMERIC(20,15),
    ex_from                     CHAR(8),
    ex_to                       CHAR(8),
    wr_amt                      NUMERIC(30,13),
    ncr_org_c                   VARCHAR(1),
    ncr_org_nm                  VARCHAR(100),
    ncr_bond_gbn                VARCHAR(1),
    ncr_bond_gbn_nm             VARCHAR(100),
    float_bond_yn               VARCHAR(1),
    re_float_bond_yn            VARCHAR(1),
    pvpl_bond_yn                VARCHAR(1),
    st_con_yn                   VARCHAR(1),
    chng_int_bd_yn              VARCHAR(1),
    sepa_yn                     VARCHAR(1),
    couponrate                  NUMERIC(20,15),
    fix_int_rate                NUMERIC(20,15),
    float_rate                  NUMERIC(20,15),
    nperi_intdt                 CHAR(8),
    cntr_cfm_dt                 CHAR(8),
    puis_strdt                  CHAR(8),
    puis_cmpdt                  CHAR(8),
    acquisition_date            CHAR(8),
    udwr_sec_qty                NUMERIC(20,0),
    sale_cfm_sec_qty            NUMERIC(20,0),
    isu_amt                     NUMERIC(30,13),
    rp_demdt                    CHAR(8),
    tot_buyf_unit               NUMERIC(20,0),
    buyf_unit                   NUMERIC(20,0),
    sale_unit                   NUMERIC(20,0),
    nsale_unit                  NUMERIC(20,0),
    sale_rate                   NUMERIC(20,15),
    nsale_rate                  NUMERIC(20,15),
    sale_evamt                  NUMERIC(30,13),
    nsale_evamt                 NUMERIC(30,13),
    loan_limit_wght             NUMERIC(20,15),
    est_limit_wght              NUMERIC(20,15),
    tagast_limit_wght           NUMERIC(20,15),
    etc_limit_wght              NUMERIC(20,15),
    stk_limit_wght              NUMERIC(20,15),
    bond_limit_wght             NUMERIC(20,15),
    puis_limit_wght             NUMERIC(20,15),
    pris_limit_wght             NUMERIC(20,15),
    float_ast_limit_wght        NUMERIC(20,15),
    fx_limit_wght               NUMERIC(20,15),
    cash_limit_wght             NUMERIC(20,15),
    unsure_limit_wght           NUMERIC(20,15),
    mon3_af_rp_unable_limit_wght        NUMERIC(20,15),
    trust_apart_deposit_limit_wght      NUMERIC(20,15),
    set_sl_risk_gbn             VARCHAR(2),
    set_sl_risk_gbn_nm          VARCHAR(100),
    gen_underlying_asset        VARCHAR(30),
    gen_underlying_asset_nm     VARCHAR(100),
    strike_price                NUMERIC(30,13),
    bs_prc                      NUMERIC(30,13),
    call_put_type               NUMERIC(1,0),
    call_put_name               VARCHAR(100),
    delta                       NUMERIC(30,13),
    gamma                       NUMERIC(30,13),
    vega                        NUMERIC(30,13),
    implied_vol                 NUMERIC(20,15),
    vol                         NUMERIC(20,15),
    cntr_factor                 NUMERIC(20,0),
    cds_hedge_slct              VARCHAR(1),
    cds_hedge_slct_nm           VARCHAR(100),
    cr_con_dls_yn               VARCHAR(1),
    item_lclas_cd               VARCHAR(2),
    item_lclas_nm               VARCHAR(100),
    item_mclas_cd               VARCHAR(2),
    item_mclas_nm               VARCHAR(100),
    item_sclas_cd               VARCHAR(2),
    item_sclas_nm               VARCHAR(100),
    item_dtl_cd                 VARCHAR(2),
    item_dtl_nm                 VARCHAR(100),
    mr_item_lclas_cd            VARCHAR(2),
    mr_item_lclas_nm            VARCHAR(100),
    mr_item_mclas_cd            VARCHAR(2),
    mr_item_mclas_nm            VARCHAR(100),
    mr_item_sclas_cd            VARCHAR(2),
    mr_item_sclas_nm            VARCHAR(100),
    mr_item_dtl_cd              VARCHAR(2),
    mr_item_dtl_nm              VARCHAR(100),
    cr_item_lclas_cd            VARCHAR(2),
    cr_item_lclas_nm            VARCHAR(100),
    cr_item_mclas_cd            VARCHAR(2),
    cr_item_mclas_nm            VARCHAR(100),
    cr_item_sclas_cd            VARCHAR(2),
    cr_item_sclas_nm            VARCHAR(100),
    cr_item_dtl_cd              VARCHAR(2),
    cr_item_dtl_nm              VARCHAR(100),
    st_risk_yn                  VARCHAR(1),
    st_mprf_tr_risk_yn          VARCHAR(1),
    st_udwr_risk_yn             VARCHAR(1),
    ir_risk_yn                  VARCHAR(1),
    ir_specific_risk_yn         VARCHAR(1),
    ir_gen_risk_yn              VARCHAR(1),
    ir_udwr_risk_yn             VARCHAR(1),
    fx_risk_yn                  VARCHAR(1),
    set_pssn_risk_yn            VARCHAR(1),
    set_sale_risk_yn            VARCHAR(1),
    gen_prod_risk_yn            VARCHAR(1),
    opt_risk_yn                 VARCHAR(1),
    deep_otm_risk_yn            VARCHAR(1),
    st_specific_risk_val        NUMERIC(20,15),
    st_specific_risk_amt        NUMERIC(30,13),
    st_gen_risk_val             NUMERIC(20,15),
    st_gen_risk_amt             NUMERIC(30,13),
    st_mprf_tr_risk_val         NUMERIC(20,15),
    st_mprf_tr_risk_amt         NUMERIC(30,13),
    st_cncr_risk_val            NUMERIC(20,15),
    st_cncr_risk_amt            NUMERIC(30,13),
    st_udwr_adj_rat             NUMERIC(20,15),
    st_udwr_risk_amt            NUMERIC(30,13),
    ir_specific_risk_val        NUMERIC(20,15),
    ir_specific_risk_amt        NUMERIC(30,13),
    ncr_ir_grp_gbn              VARCHAR(1),
    ncr_ir_grp_nm               VARCHAR(100),
    grp_hrz_dis                 NUMERIC(20,15),
    nrby_grp_hrz_dis            NUMERIC(20,15),
    tot_hrz_dis                 NUMERIC(20,15),
    assmd_ir_chg_rate           NUMERIC(20,15),
    ir_gen_risk_val             NUMERIC(20,15),
    ir_gen_risk_amt             NUMERIC(30,13),
    ir_udwr_adj_rat             NUMERIC(20,15),
    ir_udwr_risk_amt            NUMERIC(30,13),
    fx_curr_risk_val            NUMERIC(20,15),
    fx_curr_risk_amt            NUMERIC(30,13),
    fx_gold_risk_val            NUMERIC(20,15),
    fx_gold_risk_amt            NUMERIC(30,13),
    set_pssn_risk_val           NUMERIC(20,15),
    set_pssn_risk_amt           NUMERIC(30,13),
    set_sale_risk_val           NUMERIC(20,15),
    set_sale_risk_amt           NUMERIC(30,13),
    gen_tot_risk_val            NUMERIC(20,15),
    gen_net_risk_val            NUMERIC(20,15),
    gen_prod_risk_amt           NUMERIC(30,13),
    opt_gamma_risk_val          NUMERIC(20,15),
    opt_gamma_risk_amt          NUMERIC(30,13),
    opt_vega_risk_val           NUMERIC(20,15),
    opt_vega_risk_amt           NUMERIC(30,13),
    opt_dpo_prc_risk_amt        NUMERIC(30,13),
    aq_deri_type                CHAR(4),
    ir_sp_due_cd                VARCHAR(100),
    proc_risk_type              VARCHAR(100),
    offset_grp                  VARCHAR(100),
    aggr_sp_cd                  VARCHAR(100),
    aggr_gen_cd                 VARCHAR(100),
    ref_logic_id                VARCHAR(1000),
    proc_log                    VARCHAR(4000),
    bo_position_file_type       VARCHAR(100),
    bo_position_file_name       VARCHAR(100),
    bo_position_file_db         VARCHAR(100),
    sys_code01 VARCHAR(100), sys_code02 VARCHAR(100), sys_code03 VARCHAR(100),
    sys_code04 VARCHAR(100), sys_code05 VARCHAR(100), sys_code06 VARCHAR(100),
    sys_code07 VARCHAR(100), sys_code08 VARCHAR(100), sys_code09 VARCHAR(100),
    sys_code10 VARCHAR(100), sys_code11 VARCHAR(100), sys_code12 VARCHAR(100),
    sys_code13 VARCHAR(100), sys_code14 VARCHAR(100), sys_code15 VARCHAR(100),
    sys_amt01 NUMERIC(30,13), sys_amt02 NUMERIC(30,13), sys_amt03 NUMERIC(30,13),
    sys_amt04 NUMERIC(30,13), sys_amt05 NUMERIC(30,13), sys_amt06 NUMERIC(30,13),
    sys_amt07 NUMERIC(30,13), sys_amt08 NUMERIC(30,13), sys_amt09 NUMERIC(30,13),
    sys_amt10 NUMERIC(30,13), sys_amt11 NUMERIC(30,13), sys_amt12 NUMERIC(30,13),
    sys_amt13 NUMERIC(30,13), sys_amt14 NUMERIC(30,13), sys_amt15 NUMERIC(30,13),
    cust_add_info01 VARCHAR(50), cust_add_info02 VARCHAR(50), cust_add_info03 VARCHAR(50),
    cust_add_info04 VARCHAR(50), cust_add_info05 VARCHAR(50), cust_add_info06 VARCHAR(50),
    cust_add_info07 VARCHAR(50), cust_add_info08 VARCHAR(50), cust_add_info09 VARCHAR(50),
    cust_add_info10 VARCHAR(50), cust_add_info11 VARCHAR(50), cust_add_info12 VARCHAR(50),
    cust_add_info13 VARCHAR(50), cust_add_info14 VARCHAR(50), cust_add_info15 VARCHAR(50),
    cust_amt01 NUMERIC(30,13), cust_amt02 NUMERIC(30,13), cust_amt03 NUMERIC(30,13),
    cust_amt04 NUMERIC(30,13), cust_amt05 NUMERIC(30,13), cust_amt06 NUMERIC(30,13),
    cust_amt07 NUMERIC(30,13), cust_amt08 NUMERIC(30,13), cust_amt09 NUMERIC(30,13),
    cust_amt10 NUMERIC(30,13), cust_amt11 NUMERIC(30,13), cust_amt12 NUMERIC(30,13),
    cust_amt13 NUMERIC(30,13), cust_amt14 NUMERIC(30,13), cust_amt15 NUMERIC(30,13),
    hdwr_yn                     VARCHAR(1),
    remk_ctnt                   VARCHAR(1000),
    dlmn_eno                    VARCHAR(9),
    dl_tm                       TIMESTAMP,
    dl_term_no                  VARCHAR(40),
    dl_mtnb_cd                  VARCHAR(5),
    PRIMARY KEY (std_date, org_code, con_sep_clcd, port_no, ncr_stress_no, bo_item_code)
);
"""

COLUMN_COMMENTS = {
    "std_date": "기준일자", "org_code": "사무소코드",
    "con_sep_clcd": "연결별도구분코드", "port_no": "포트폴리오번호",
    "ncr_stress_no": "NCR스트레스번호", "bo_item_code": "익스포져ID",
    "con_sep_clnm": "연결별도구분명",
    "bo_dept_cd01": "BO조직코드01", "bo_dept_nm01": "BO조직코드명01",
    "bo_dept_cd02": "BO조직코드02", "bo_dept_nm02": "BO조직코드명02",
    "bo_dept_cd03": "BO조직코드03", "bo_dept_nm03": "BO조직코드명03",
    "bo_dept_cd04": "BO조직코드04", "bo_dept_nm04": "BO조직코드명04",
    "bo_dept_cd05": "BO조직코드05", "bo_dept_nm05": "BO조직코드명05",
    "biz_area_cd": "업무영역코드(NCR)", "biz_area_nm": "업무영역명(NCR)",
    "item_code": "종목코드", "item_name": "종목명",
    "fund_code": "펀드코드", "fund_name": "펀드명",
    "cust_fund_code": "고객펀드코드", "cust_fund_name": "고객펀드명",
    "bo_good_cd01": "BO상품코드01", "bo_good_nm01": "BO상품코드명01",
    "bo_good_cd02": "BO상품코드02", "bo_good_nm02": "BO상품코드명02",
    "bo_good_cd03": "BO상품코드03", "bo_good_nm03": "BO상품코드명03",
    "good_grp1": "상품분류1", "good_grp_nm1": "상품분류명1",
    "good_grp2": "상품분류2", "good_grp_nm2": "상품분류명2",
    "good_grp3": "상품분류3", "good_grp_nm3": "상품분류명3",
    "bo_acct_cd01": "BO계정코드01", "bo_acct_nm01": "BO계정코드명01",
    "acct_oper_type": "계정처리유형", "acct_oper_name": "계정처리유형명",
    "sub_item_code": "하위종목코드", "sub_item_name": "하위종목명",
    "underlying_id": "기초자산ID", "underlying_name": "기초자산명",
    "underlying_grp": "기초자산그룹", "underlying_grp_name": "기초자산그룹명",
    "deal_type": "매매유형", "deal_name": "매매유형명",
    "trade_date": "거래일자", "due_date": "만기일자",
    "srvl_dcnt": "연환산일수(일)", "srvl_mcnt": "연환산일수(월)",
    "currency_code": "통화코드", "fx_rate": "환율",
    "cpty_code": "거래상대방코드", "cpty_name": "거래상대방명",
    "cpty_gbn": "거래상대방구분(NCR)", "cpty_gbn_nm": "거래상대방구분명(NCR)",
    "cover_yn": "결손보전대상여부", "sp_rlt_yn": "특수관계인여부",
    "firm_grp_id": "법인그룹ID", "firm_grp_name": "법인그룹명",
    "cpty_crdt_eval_grad": "거래상대방신용등급코드",
    "cpty_crdt_eval_grad_nm": "거래상대방신용등급명",
    "sec_crdt_eval_grad": "유가증권신용등급코드",
    "sec_crdt_eval_grad_nm": "유가증권신용등급명",
    "cds_ref_crdt_eval_grad": "CDS준거자산신용등급코드",
    "cds_ref_crdt_eval_grad_nm": "CDS준거자산신용등급명",
    "ncr_grad_cd": "NCR신용등급코드", "ncr_grad_cd_nm": "NCR신용등급명",
    "face_unit": "액면단위", "face_amt": "액면금액(수량)",
    "market_price": "시장단가", "book_amt": "장부금액",
    "notional_amt": "명목금액", "market_amt": "시장금액",
    "eval_pl_amt": "평가손익금액", "posi_amt": "포지션금액",
    "fx_risk_posi_amt": "외환위험포지션금액",
    "delta_posi_amt": "델타포지션금액", "gamma_posi_amt": "감마포지션금액",
    "vega_posi_amt": "베가포지션금액",
    "bef_std_amt": "상계전포지션기준금액(부호반영, 옵션인경우 델타포지션금액)",
    "std_amt": "상계후포지션기준금액(부호반영, 옵션인경우 델타포지션금액)",
    "inter_yn": "내부거래여부", "etf_yn": "ETF여부", "lvrg_rate": "레버리지비율(%)",
    "ncr_st_gbn": "NCR주식구분", "ncr_st_gbn_nm": "NCR주식구분명",
    "nat_cd": "국가코드(NCR)", "nat_nm": "국가명(NCR)",
    "qlfc_mkt_cd": "적격시장코드", "qlfc_mkt_nm": "적격시장명",
    "mkt_ind_cd": "시장지수코드", "mkt_ind_nm": "시장지수명",
    "bskt_mkt_tot_amt": "바스켓시가총액", "bskt_beta": "바스켓베타",
    "bskt_r2": "바스켓설명력",
    "float_sfcc_yn": "유동성충족여부", "dvrsf_sfcc_yn": "분산도충족여부",
    "buy_item_gbn": "매수종목구분", "buy_item_code": "매수종목코드",
    "buy_item_name": "매수종목명", "buy_position_amt": "매수포지션금액",
    "sel_item_gbn": "매도종목구분", "sel_item_code": "매도종목코드",
    "sel_item_name": "매도종목명", "sel_position_amt": "매도포지션금액",
    "mprf_tr_posi_amt": "차익거래포지션금액",
    "ind_mkt_tot_amt": "주가지수시가총액", "item_pos_qty": "종목별포지션수량",
    "list_st_qty": "상장주식수", "item_list_st_qty": "종목별상장주식수",
    "st_change_ratio": "주식전환비율",
    "ex_from": "행사가능초일", "ex_to": "행사가능말일",
    "wr_amt": "신주인수권금액",
    "ncr_org_c": "NCR기관코드", "ncr_org_nm": "NCR기관명",
    "ncr_bond_gbn": "NCR채권구분", "ncr_bond_gbn_nm": "NCR채권구분명",
    "float_bond_yn": "유동화채권여부", "re_float_bond_yn": "재유동화채권여부",
    "pvpl_bond_yn": "사모채권여부", "st_con_yn": "주식연계여부",
    "chng_int_bd_yn": "변동금리채권여부", "sepa_yn": "분리형여부",
    "couponrate": "표면금리", "fix_int_rate": "고정금리", "float_rate": "변동금리",
    "nperi_intdt": "차기이자일", "cntr_cfm_dt": "계약확정일",
    "puis_strdt": "공모개시일", "puis_cmpdt": "공모완료일",
    "acquisition_date": "취득일자", "udwr_sec_qty": "인수증권수",
    "sale_cfm_sec_qty": "판매확정증권수", "isu_amt": "발행가", "rp_demdt": "환매청구일",
    "tot_buyf_unit": "총설정좌수", "buyf_unit": "설정좌수",
    "sale_unit": "매각좌수", "nsale_unit": "미매각좌수",
    "sale_rate": "매각비율(%)", "nsale_rate": "미매각비율(%)",
    "sale_evamt": "매각분평가금액", "nsale_evamt": "미매각분평가금액",
    "loan_limit_wght": "편입한도비율(대출채권관련)",
    "est_limit_wght": "편입한도비율(부동산)",
    "tagast_limit_wght": "편입한도비율(유형자산 및 사회기반시설)",
    "etc_limit_wght": "편입한도비율(기타)",
    "stk_limit_wght": "편입한도비율(주식)",
    "bond_limit_wght": "편입한도비율(채권)",
    "puis_limit_wght": "편입한도비율(공모집합)",
    "pris_limit_wght": "편입한도비율(사모집합)",
    "float_ast_limit_wght": "편입한도비율(유동성자산)",
    "fx_limit_wght": "편입한도비율(외국통화)",
    "cash_limit_wght": "편입한도비율(현금)",
    "unsure_limit_wght": "편입한도비율(편입비율파악곤란)",
    "mon3_af_rp_unable_limit_wght": "편입한도비율(3개월이내환매불가)",
    "trust_apart_deposit_limit_wght": "편입한도비율(신탁방식고객예탁금별도예치금)",
    "set_sl_risk_gbn": "집합투자증권판매위험구분",
    "set_sl_risk_gbn_nm": "집합투자증권판매위험구분명",
    "gen_underlying_asset": "일반상품기초자산유형",
    "gen_underlying_asset_nm": "일반상품기초자산유형명",
    "strike_price": "행사가", "bs_prc": "기초가격",
    "call_put_type": "옵션타입(1:콜 그외 풋)", "call_put_name": "옵션타입명",
    "delta": "Delta", "gamma": "Gamma", "vega": "Vega",
    "implied_vol": "내재변동성", "vol": "변동성", "cntr_factor": "계약승수",
    "cds_hedge_slct": "CDS헷지구분", "cds_hedge_slct_nm": "CDS헷지구분명",
    "cr_con_dls_yn": "신용연계DLS여부",
    "item_lclas_cd": "항목대분류코드", "item_lclas_nm": "항목대분류명",
    "item_mclas_cd": "항목중분류코드", "item_mclas_nm": "항목중분류명",
    "item_sclas_cd": "항목소분류코드", "item_sclas_nm": "항목소분류명",
    "item_dtl_cd": "항목상세분류코드", "item_dtl_nm": "항목상세분류명",
    "mr_item_lclas_cd": "시장항목대분류코드", "mr_item_lclas_nm": "시장항목대분류명",
    "mr_item_mclas_cd": "시장항목중분류코드", "mr_item_mclas_nm": "시장항목중분류명",
    "mr_item_sclas_cd": "시장항목소분류코드", "mr_item_sclas_nm": "시장항목소분류명",
    "mr_item_dtl_cd": "시장항목상세분류코드", "mr_item_dtl_nm": "시장항목상세분류명",
    "cr_item_lclas_cd": "신용항목대분류코드", "cr_item_lclas_nm": "신용항목대분류명",
    "cr_item_mclas_cd": "신용항목중분류코드", "cr_item_mclas_nm": "신용항목중분류명",
    "cr_item_sclas_cd": "신용항목소분류코드", "cr_item_sclas_nm": "신용항목소분류명",
    "cr_item_dtl_cd": "신용항목상세분류코드", "cr_item_dtl_nm": "신용항목상세분류명",
    "st_risk_yn": "주식위험여부", "st_mprf_tr_risk_yn": "주식차익거래위험여부",
    "st_udwr_risk_yn": "주식인수위험여부", "ir_risk_yn": "금리위험여부",
    "ir_specific_risk_yn": "금리개별위험여부", "ir_gen_risk_yn": "금리일반위험여부",
    "ir_udwr_risk_yn": "금리인수위험여부", "fx_risk_yn": "외환위험여부",
    "set_pssn_risk_yn": "집합보유위험여부", "set_sale_risk_yn": "집합판매위험여부",
    "gen_prod_risk_yn": "일반상품위험여부", "opt_risk_yn": "옵션위험여부",
    "deep_otm_risk_yn": "깊은외가격옵션위험여부",
    "st_specific_risk_val": "주식개별위험값", "st_specific_risk_amt": "주식개별위험액",
    "st_gen_risk_val": "주식일반위험값", "st_gen_risk_amt": "주식일반위험액",
    "st_mprf_tr_risk_val": "주식차익거래위험값", "st_mprf_tr_risk_amt": "주식차익거래위험액",
    "st_cncr_risk_val": "주식집중위험값", "st_cncr_risk_amt": "주식집중위험액",
    "st_udwr_adj_rat": "주식인수조정비율", "st_udwr_risk_amt": "주식인수위험액",
    "ir_specific_risk_val": "금리개별위험값", "ir_specific_risk_amt": "금리개별위험액",
    "ncr_ir_grp_gbn": "NCR금리그룹구분", "ncr_ir_grp_nm": "NCR금리그룹명",
    "grp_hrz_dis": "그룹자본할당률", "nrby_grp_hrz_dis": "인접그룹자본할당률",
    "tot_hrz_dis": "전체자본할당률", "assmd_ir_chg_rate": "상정금리변동폭",
    "ir_gen_risk_val": "금리일반위험값", "ir_gen_risk_amt": "금리일반위험액",
    "ir_udwr_adj_rat": "금리인수조정비율", "ir_udwr_risk_amt": "금리인수위험액",
    "fx_curr_risk_val": "외환통화위험값", "fx_curr_risk_amt": "외환통화위험액",
    "fx_gold_risk_val": "외환금위험값", "fx_gold_risk_amt": "외환금위험액",
    "set_pssn_risk_val": "집합투자위험값", "set_pssn_risk_amt": "집투개별위험액",
    "set_sale_risk_val": "집합판매위험값", "set_sale_risk_amt": "집합판매위험액",
    "gen_tot_risk_val": "일반총포지션위험값", "gen_net_risk_val": "일반순포지션위험값",
    "gen_prod_risk_amt": "일반상품위험액",
    "opt_gamma_risk_val": "감마위험값: 기초자산- 주식,외환:8%, 금리옵션:상정금리변동폭",
    "opt_gamma_risk_amt": "옵션감마위험액",
    "opt_vega_risk_val": "베가위험값: 0.25", "opt_vega_risk_amt": "옵션베가위험액",
    "opt_dpo_prc_risk_amt": "옵션깊은외가격위험액",
    "aq_deri_type": "상품타입", "ir_sp_due_cd": "금리개별위험만기구분코드",
    "proc_risk_type": "NCR_위험설정구분", "offset_grp": "상계그룹",
    "aggr_sp_cd": "집계구분코드-개별", "aggr_gen_cd": "집계구분코드-일반",
    "ref_logic_id": "참고로직ID", "proc_log": "처리함수로그",
    "bo_position_file_type": "BO보유자산파일유형",
    "bo_position_file_name": "BO보유자산파일유형명",
    "bo_position_file_db": "BO보유자산파일DB명",
    **{f"sys_code{i:02d}": f"SYS_CODE{i:02d}" for i in range(1, 16)},
    **{f"sys_amt{i:02d}": f"SYS_AMT{i:02d}" for i in range(1, 16)},
    **{f"cust_add_info{i:02d}": f"고객추가정보{i:02d}" for i in range(1, 16)},
    **{f"cust_amt{i:02d}": f"CUST_AMT{i:02d}" for i in range(1, 16)},
    "hdwr_yn": "수기처리여부", "remk_ctnt": "참조(REMK_CTNT)",
    "dlmn_eno": "처리자", "dl_tm": "처리일시",
    "dl_term_no": "처리단말번호", "dl_mtnb_cd": "처리부서",
}

if __name__ == "__main__":
    conn = psycopg2.connect(os.getenv("DATABASE_URL"))
    cur = conn.cursor()

    cur.execute(DDL)
    cur.execute("COMMENT ON TABLE td_irriskmr IS '시장위험 산출 데이터'")
    for col, cmt in COLUMN_COMMENTS.items():
        cur.execute(f"COMMENT ON COLUMN td_irriskmr.{col} IS %s", (cmt,))

    conn.commit()

    cur.execute(
        "SELECT COUNT(*) FROM information_schema.columns WHERE table_name='td_irriskmr'"
    )
    print(f"td_irriskmr {cur.fetchone()[0]} columns created")
    conn.close()
