"""
create_td_irriskcr.py - TD_IRRISKCR 테이블 생성
실행: python db/create_td_irriskcr.py
"""
import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

DDL = """
DROP TABLE IF EXISTS td_irriskcr;
CREATE TABLE td_irriskcr (
    std_date                CHAR(8)         NOT NULL,
    org_code                VARCHAR(6)      NOT NULL,
    con_sep_clcd            VARCHAR(1)      NOT NULL,
    port_no                 NUMERIC(20,0)   NOT NULL,
    ncr_stress_no           NUMERIC(20,0)   NOT NULL,
    bo_item_code            VARCHAR(100)    NOT NULL,
    con_sep_clnm            VARCHAR(200),
    bo_dept_cd01            VARCHAR(20),
    bo_dept_nm01            VARCHAR(100),
    bo_dept_cd02            VARCHAR(20),
    bo_dept_nm02            VARCHAR(100),
    bo_dept_cd03            VARCHAR(20),
    bo_dept_nm03            VARCHAR(100),
    bo_dept_cd04            VARCHAR(20),
    bo_dept_nm04            VARCHAR(100),
    bo_dept_cd05            VARCHAR(20),
    bo_dept_nm05            VARCHAR(100),
    biz_area_cd             VARCHAR(4),
    biz_area_nm             VARCHAR(100),
    item_code               VARCHAR(100),
    item_name               VARCHAR(200),
    fund_code               VARCHAR(80),
    fund_name               VARCHAR(100),
    cust_fund_code          VARCHAR(100),
    cust_fund_name          VARCHAR(100),
    bo_good_cd01            VARCHAR(20),
    bo_good_nm01            VARCHAR(100),
    bo_good_cd02            VARCHAR(20),
    bo_good_nm02            VARCHAR(100),
    bo_good_cd03            VARCHAR(20),
    bo_good_nm03            VARCHAR(100),
    good_grp1               VARCHAR(6),
    good_grp_nm1            VARCHAR(100),
    good_grp2               VARCHAR(6),
    good_grp_nm2            VARCHAR(100),
    good_grp3               VARCHAR(6),
    good_grp_nm3            VARCHAR(100),
    bo_acct_cd01            VARCHAR(20),
    bo_acct_nm01            VARCHAR(100),
    acct_oper_type          VARCHAR(10),
    acct_oper_name          VARCHAR(100),
    deal_type               CHAR(1),
    deal_name               VARCHAR(100),
    trade_date              CHAR(8),
    settle_date             CHAR(8),
    over_settle_dcnt        NUMERIC(20,15),
    effect_date             CHAR(8),
    due_date                CHAR(8),
    srvl_dcnt               NUMERIC(20,15),
    srvl_mcnt               NUMERIC(20,15),
    cpty_code               VARCHAR(50),
    cpty_name               VARCHAR(500),
    cpty_gbn                VARCHAR(2),
    cpty_gbn_nm             VARCHAR(100),
    cover_yn                CHAR(1),
    sp_rlt_yn               VARCHAR(1),
    ksic_code               VARCHAR(10),
    ksic_name               VARCHAR(100),
    firm_grp_id             VARCHAR(50),
    firm_grp_name           VARCHAR(500),
    cpty_crdt_eval_grad     VARCHAR(10),
    cpty_crdt_eval_grad_nm  VARCHAR(10),
    sec_crdt_eval_grad      VARCHAR(10),
    sec_crdt_eval_grad_nm   VARCHAR(10),
    cds_ref_crdt_eval_grad  VARCHAR(10),
    cds_ref_crdt_eval_grad_nm VARCHAR(10),
    ncr_grad_cd             VARCHAR(10),
    ncr_grad_cd_nm          VARCHAR(10),
    crt_cpty_code           VARCHAR(50),
    crt_cpty_name           VARCHAR(500),
    crt_cpty_gbn            VARCHAR(2),
    crt_cpty_gbn_nm         VARCHAR(100),
    crt_cover_yn            CHAR(1),
    crt_firm_grp_id         VARCHAR(50),
    crt_firm_grp_name       VARCHAR(500),
    crt_cpty_eval_grad      VARCHAR(10),
    crt_cpty_eval_grad_nm   VARCHAR(10),
    face_amt                NUMERIC(30,13),
    market_price            NUMERIC(30,13),
    book_amt                NUMERIC(30,13),
    notional_amt            NUMERIC(30,13),
    market_amt              NUMERIC(30,13),
    eval_pl_amt             NUMERIC(30,13),
    cash_dfamt              NUMERIC(30,13),
    crdt_int_upamt          NUMERIC(30,13),
    loan_int_upamt          NUMERIC(30,13),
    fs_cva                  NUMERIC(30,13),
    cva                     NUMERIC(30,13),
    inter_yn                CHAR(1),
    resi_pri_amt            NUMERIC(30,13),
    ccp_yn                  CHAR(1),
    brst_sel_qty            NUMERIC(20,0),
    rp_buy_amt              NUMERIC(30,13),
    rp_sel_amt              NUMERIC(30,13),
    crdt_give_amt           NUMERIC(30,13),
    ccf_grp                 VARCHAR(10),
    ccf_grp_nm              VARCHAR(100),
    ccf_code                VARCHAR(10),
    ccf_name                VARCHAR(100),
    due_type                VARCHAR(10),
    due_type_nm             VARCHAR(100),
    ccf_rate                NUMERIC(20,15),
    engg_amt                NUMERIC(30,13),
    engg_end_date           CHAR(8),
    dep_yn                  VARCHAR(1),
    dep_amt                 NUMERIC(30,13),
    crdt_enhnc_yn           VARCHAR(1),
    grnt_gbn                VARCHAR(2),
    grnt_gbn_nm             VARCHAR(100),
    grnt_amt                NUMERIC(30,13),
    coll_allo_amt           NUMERIC(30,13),
    appl_coll_allo_amt      NUMERIC(30,13),
    item_lclas_cd           VARCHAR(2),
    item_lclas_nm           VARCHAR(100),
    item_mclas_cd           VARCHAR(2),
    item_mclas_nm           VARCHAR(100),
    item_sclas_cd           VARCHAR(2),
    item_sclas_nm           VARCHAR(100),
    item_dtl_cd             VARCHAR(2),
    item_dtl_nm             VARCHAR(100),
    mr_item_lclas_cd        VARCHAR(2),
    mr_item_lclas_nm        VARCHAR(100),
    mr_item_mclas_cd        VARCHAR(2),
    mr_item_mclas_nm        VARCHAR(100),
    mr_item_sclas_cd        VARCHAR(2),
    mr_item_sclas_nm        VARCHAR(100),
    mr_item_dtl_cd          VARCHAR(2),
    mr_item_dtl_nm          VARCHAR(100),
    cr_item_lclas_cd        VARCHAR(2),
    cr_item_lclas_nm        VARCHAR(100),
    cr_item_mclas_cd        VARCHAR(2),
    cr_item_mclas_nm        VARCHAR(100),
    cr_item_sclas_cd        VARCHAR(2),
    cr_item_sclas_nm        VARCHAR(100),
    cr_item_dtl_cd          VARCHAR(2),
    cr_item_dtl_nm          VARCHAR(100),
    dpstr_risk_yn           VARCHAR(1),
    sec_risk_yn             VARCHAR(1),
    rp_risk_yn              VARCHAR(1),
    crdt_give_risk_yn       VARCHAR(1),
    inct_risk_yn            VARCHAR(1),
    prdv_grnt_risk_yn       VARCHAR(1),
    lamt_risk_yn            VARCHAR(1),
    loan_risk_yn            VARCHAR(1),
    etc_asset_risk_yn       CHAR(1),
    crdt_cncr_risk_yn       VARCHAR(1),
    ir_specific_risk_val    NUMERIC(20,15),
    ir_gen_risk_val         NUMERIC(20,15),
    st_specific_risk_val    NUMERIC(20,15),
    st_gen_risk_val         NUMERIC(20,15),
    mkt_risk_val            NUMERIC(20,15),
    crdt_chng_amt           NUMERIC(30,13),
    crdt_risk_val           NUMERIC(20,15),
    crdt_risk_amt           NUMERIC(30,13),
    crdt_mtgt_amt           NUMERIC(30,13),
    crdt_mtgt_val           NUMERIC(20,15),
    crdt_mtgt_risk_amt      NUMERIC(30,13),
    coll_grp                VARCHAR(100),
    coll_alloc_cd           VARCHAR(100),
    coll_src_cd             VARCHAR(100),
    proc_risk_type          VARCHAR(100),
    offset_grp              VARCHAR(100),
    ref_logic_id            VARCHAR(1000),
    proc_log                VARCHAR(4000),
    bo_position_file_type   VARCHAR(100),
    bo_position_file_name   VARCHAR(100),
    bo_position_file_db     VARCHAR(100),
    sys_code01 VARCHAR(100), sys_code02 VARCHAR(100), sys_code03 VARCHAR(100),
    sys_code04 VARCHAR(100), sys_code05 VARCHAR(100), sys_code06 VARCHAR(100),
    sys_code07 VARCHAR(100), sys_code08 VARCHAR(100), sys_code09 VARCHAR(100),
    sys_code10 VARCHAR(100), sys_code11 VARCHAR(100), sys_code12 VARCHAR(100),
    sys_code13 VARCHAR(100), sys_code14 VARCHAR(100), sys_code15 VARCHAR(100),
    sys_amt01 NUMERIC(30,13), sys_amt02 NUMERIC(30,13), sys_amt03 NUMERIC(30,13),
    sys_amt04 NUMERIC(30,13), sys_amt05 NUMERIC(30,13), sys_amt06 NUMERIC(30,13),
    sys_amt07 NUMERIC(30,13), sys_amt08 NUMERIC(30,13), sys_amt09 NUMERIC(30,13),
    sys_amt10 NUMERIC(30,13), sys_amt11 NUMERIC(30,13), sys_amt12 NUMERIC(30,13),
    sys_amt13 NUMERIC(30,13), sys_amt14 NUMERIC(30,13), sys_amt15 NUMERIC(30,13),
    cust_add_info01 VARCHAR(50), cust_add_info02 VARCHAR(50), cust_add_info03 VARCHAR(50),
    cust_add_info04 VARCHAR(50), cust_add_info05 VARCHAR(50), cust_add_info06 VARCHAR(50),
    cust_add_info07 VARCHAR(50), cust_add_info08 VARCHAR(50), cust_add_info09 VARCHAR(50),
    cust_add_info10 VARCHAR(50), cust_add_info11 VARCHAR(50), cust_add_info12 VARCHAR(50),
    cust_add_info13 VARCHAR(50), cust_add_info14 VARCHAR(50), cust_add_info15 VARCHAR(50),
    cust_amt01 NUMERIC(30,13), cust_amt02 NUMERIC(30,13), cust_amt03 NUMERIC(30,13),
    cust_amt04 NUMERIC(30,13), cust_amt05 NUMERIC(30,13), cust_amt06 NUMERIC(30,13),
    cust_amt07 NUMERIC(30,13), cust_amt08 NUMERIC(30,13), cust_amt09 NUMERIC(30,13),
    cust_amt10 NUMERIC(30,13), cust_amt11 NUMERIC(30,13), cust_amt12 NUMERIC(30,13),
    cust_amt13 NUMERIC(30,13), cust_amt14 NUMERIC(30,13), cust_amt15 NUMERIC(30,13),
    hdwr_yn                 VARCHAR(1),
    remk_ctnt               VARCHAR(1000),
    dlmn_eno                VARCHAR(9),
    dl_tm                   TIMESTAMP,
    dl_term_no              VARCHAR(40),
    dl_mtnb_cd              VARCHAR(5),
    PRIMARY KEY (std_date, org_code, con_sep_clcd, port_no, ncr_stress_no, bo_item_code)
);
"""

COLUMN_COMMENTS = {
    "std_date": "기준일자", "org_code": "사무소코드",
    "con_sep_clcd": "연결별도구분코드", "port_no": "포트폴리오번호",
    "ncr_stress_no": "NCR스트레스번호", "bo_item_code": "익스포져ID",
    "con_sep_clnm": "연결별도구분명",
    "bo_dept_cd01": "BO조직코드01", "bo_dept_nm01": "BO조직코드명01",
    "bo_dept_cd02": "BO조직코드02", "bo_dept_nm02": "BO조직코드명02",
    "bo_dept_cd03": "BO조직코드03", "bo_dept_nm03": "BO조직코드명03",
    "bo_dept_cd04": "BO조직코드04", "bo_dept_nm04": "BO조직코드명04",
    "bo_dept_cd05": "BO조직코드05", "bo_dept_nm05": "BO조직코드명05",
    "biz_area_cd": "업무영역코드(NCR)", "biz_area_nm": "업무영역명(NCR)",
    "item_code": "종목코드", "item_name": "종목명",
    "fund_code": "펀드코드", "fund_name": "펀드명",
    "cust_fund_code": "고객펀드코드", "cust_fund_name": "고객펀드명",
    "bo_good_cd01": "BO상품코드01", "bo_good_nm01": "BO상품코드명01",
    "bo_good_cd02": "BO상품코드02", "bo_good_nm02": "BO상품코드명02",
    "bo_good_cd03": "BO상품코드03", "bo_good_nm03": "BO상품코드명03",
    "good_grp1": "상품분류1", "good_grp_nm1": "상품분류명1",
    "good_grp2": "상품분류2", "good_grp_nm2": "상품분류명2",
    "good_grp3": "상품분류3", "good_grp_nm3": "상품분류명3",
    "bo_acct_cd01": "BO계정코드01", "bo_acct_nm01": "BO계정코드명01",
    "acct_oper_type": "계정처리유형", "acct_oper_name": "계정처리유형명",
    "deal_type": "매매유형", "deal_name": "매매유형명",
    "trade_date": "거래일자", "settle_date": "결제일자",
    "over_settle_dcnt": "결제기일경과일수(일)",
    "effect_date": "효력시작일", "due_date": "만기일자",
    "srvl_dcnt": "연환산일수(일)", "srvl_mcnt": "연환산일수(월)",
    "cpty_code": "거래상대방코드", "cpty_name": "거래상대방명",
    "cpty_gbn": "거래상대방구분(NCR)", "cpty_gbn_nm": "거래상대방구분명(NCR)",
    "cover_yn": "결손보전대상여부", "sp_rlt_yn": "특수관계인여부",
    "ksic_code": "표준산업분류코드", "ksic_name": "표준산업분류명",
    "firm_grp_id": "법인그룹ID", "firm_grp_name": "법인그룹명",
    "cpty_crdt_eval_grad": "거래상대방신용등급코드",
    "cpty_crdt_eval_grad_nm": "거래상대방신용등급명",
    "sec_crdt_eval_grad": "유가증권신용등급코드",
    "sec_crdt_eval_grad_nm": "유가증권신용등급명",
    "cds_ref_crdt_eval_grad": "CDS준거자산신용등급코드",
    "cds_ref_crdt_eval_grad_nm": "CDS준거자산신용등급명",
    "ncr_grad_cd": "NCR신용등급코드", "ncr_grad_cd_nm": "NCR신용등급명",
    "crt_cpty_code": "신용보강자코드", "crt_cpty_name": "신용보강자명",
    "crt_cpty_gbn": "신용보강자구분", "crt_cpty_gbn_nm": "신용보강자구분명",
    "crt_cover_yn": "신용보강자결손보전대상여부",
    "crt_firm_grp_id": "신용보강자법인그룹ID",
    "crt_firm_grp_name": "신용보강자법인그룹명",
    "crt_cpty_eval_grad": "신용보강자신용등급코드",
    "crt_cpty_eval_grad_nm": "신용보강자신용등급명",
    "face_amt": "액면금액(수량)", "market_price": "시장단가",
    "book_amt": "장부금액", "notional_amt": "명목금액",
    "market_amt": "시장금액", "eval_pl_amt": "평가손익금액",
    "cash_dfamt": "현금미수금액", "crdt_int_upamt": "신용이자미납금액",
    "loan_int_upamt": "대출이자미납금액",
    "fs_cva": "취득시CVA", "cva": "평가시CVA",
    "inter_yn": "내부거래여부", "resi_pri_amt": "잔여기간프리미엄",
    "ccp_yn": "CCP거래여부", "brst_sel_qty": "대차매도수량",
    "rp_buy_amt": "RP매수금액", "rp_sel_amt": "RP매도금액",
    "crdt_give_amt": "신용공여액",
    "ccf_grp": "CCF그룹", "ccf_grp_nm": "CCF그룹명",
    "ccf_code": "신용환산율(CCF)코드", "ccf_name": "신용환산율(CCF)명",
    "due_type": "만기유형", "due_type_nm": "만기유형명",
    "ccf_rate": "신용환산율(%)",
    "engg_amt": "약정금액", "engg_end_date": "약정종료일자",
    "dep_yn": "상각여부", "dep_amt": "상각금액",
    "crdt_enhnc_yn": "신용보강여부",
    "grnt_gbn": "보증구분(NCR)", "grnt_gbn_nm": "보증구분명(NCR)",
    "grnt_amt": "보증금액(NCR)",
    "coll_allo_amt": "담보인정금액", "appl_coll_allo_amt": "적용담보인정금액",
    "item_lclas_cd": "항목대분류코드", "item_lclas_nm": "항목대분류명",
    "item_mclas_cd": "항목중분류코드", "item_mclas_nm": "항목중분류명",
    "item_sclas_cd": "항목소분류코드", "item_sclas_nm": "항목소분류명",
    "item_dtl_cd": "항목상세분류코드", "item_dtl_nm": "항목상세분류명",
    "mr_item_lclas_cd": "시장항목대분류코드", "mr_item_lclas_nm": "시장항목대분류명",
    "mr_item_mclas_cd": "시장항목중분류코드", "mr_item_mclas_nm": "시장항목중분류명",
    "mr_item_sclas_cd": "시장항목소분류코드", "mr_item_sclas_nm": "시장항목소분류명",
    "mr_item_dtl_cd": "시장항목상세분류코드", "mr_item_dtl_nm": "시장항목상세분류명",
    "cr_item_lclas_cd": "신용항목대분류코드", "cr_item_lclas_nm": "신용항목대분류명",
    "cr_item_mclas_cd": "신용항목중분류코드", "cr_item_mclas_nm": "신용항목중분류명",
    "cr_item_sclas_cd": "신용항목소분류코드", "cr_item_sclas_nm": "신용항목소분류명",
    "cr_item_dtl_cd": "신용항목상세분류코드", "cr_item_dtl_nm": "신용항목상세분류명",
    "dpstr_risk_yn": "예금등위험여부", "sec_risk_yn": "유가증권대차위험여부",
    "rp_risk_yn": "RP거래위험여부", "crdt_give_risk_yn": "신용공여위험여부",
    "inct_risk_yn": "파생상품위험여부", "prdv_grnt_risk_yn": "채무보증등위험여부",
    "lamt_risk_yn": "대여금등위험여부", "loan_risk_yn": "대출채권등위험여부",
    "etc_asset_risk_yn": "기타자산위험여부", "crdt_cncr_risk_yn": "신용집중위험여부",
    "ir_specific_risk_val": "금리개별위험값", "ir_gen_risk_val": "금리일반위험값",
    "st_specific_risk_val": "주식개별위험값", "st_gen_risk_val": "주식일반위험값",
    "mkt_risk_val": "시장위험값", "crdt_chng_amt": "신용환산액",
    "crdt_risk_val": "신용위험값", "crdt_risk_amt": "신용위험액",
    "crdt_mtgt_amt": "신용경감금액", "crdt_mtgt_val": "신용경감위험값",
    "crdt_mtgt_risk_amt": "신용경감위험액",
    "coll_grp": "담보그룹", "coll_alloc_cd": "담보배분코드", "coll_src_cd": "담보원천코드",
    "proc_risk_type": "NCR_위험설정구분", "offset_grp": "상계그룹",
    "ref_logic_id": "참고로직ID", "proc_log": "처리함수로그",
    "bo_position_file_type": "BO보유자산파일유형",
    "bo_position_file_name": "BO보유자산파일유형명",
    "bo_position_file_db": "BO보유자산파일DB명",
    **{f"sys_code{i:02d}": f"SYS_CODE{i:02d}" for i in range(1, 16)},
    **{f"sys_amt{i:02d}": f"SYS_AMT{i:02d}" for i in range(1, 16)},
    **{f"cust_add_info{i:02d}": f"고객추가정보{i:02d}" for i in range(1, 16)},
    **{f"cust_amt{i:02d}": f"CUST_AMT{i:02d}" for i in range(1, 16)},
    "hdwr_yn": "수기처리여부", "remk_ctnt": "참조(REMK_CTNT)",
    "dlmn_eno": "처리자", "dl_tm": "처리일시",
    "dl_term_no": "처리단말번호", "dl_mtnb_cd": "처리부서",
}

if __name__ == "__main__":
    conn = psycopg2.connect(os.getenv("DATABASE_URL"))
    cur = conn.cursor()

    cur.execute(DDL)
    cur.execute("COMMENT ON TABLE td_irriskcr IS '신용위험 산출 데이터'")
    for col, cmt in COLUMN_COMMENTS.items():
        cur.execute(f"COMMENT ON COLUMN td_irriskcr.{col} IS %s", (cmt,))

    conn.commit()

    cur.execute(
        "SELECT COUNT(*) FROM information_schema.columns WHERE table_name='td_irriskcr'"
    )
    print(f"td_irriskcr {cur.fetchone()[0]} columns created")
    conn.close()
