import type { Collection } from "@/types/collection";

export const collections: Collection[] = [
  {
    id: "risk-management",
    name: "리스크 관리",
    description: "신용·시장·유동성·NCR 리스크 현황 대시보드",
    color: "bg-blue-500",
    textColor: "text-blue-600",
    icon: "ShieldAlert",
    createdAt: "2026-01-01",
    itemCount: 4,
    items: [
      {
        id: "credit-risk",
        title: "신용리스크 대시보드",
        description: "NPL / PD / LGD / EAD 현황 및 추이",
        type: "dashboard",
        href: "/credit-risk",
        createdAt: "2026-01-01",
        updatedAt: "2026-03-10",
        author: "리스크관리부",
        pinned: true,
      },
      {
        id: "market-risk",
        title: "시장리스크 대시보드",
        description: "VaR / 스트레스 테스트 결과",
        type: "dashboard",
        href: "/market-risk",
        createdAt: "2026-01-01",
        updatedAt: "2026-03-10",
        author: "리스크관리부",
        pinned: true,
      },
      {
        id: "liquidity-risk",
        title: "유동성리스크 대시보드",
        description: "LCR / NSFR / 만기갭 현황",
        type: "dashboard",
        href: "/liquidity-risk",
        createdAt: "2026-01-01",
        updatedAt: "2026-03-10",
        author: "리스크관리부",
        pinned: true,
      },
      {
        id: "ncr-risk",
        title: "NCR리스크 대시보드",
        description: "순자본비율 및 기타 지표",
        type: "dashboard",
        href: "/ncr-risk",
        createdAt: "2026-01-01",
        updatedAt: "2026-03-10",
        author: "리스크관리부",
        pinned: false,
      },
    ],
  },
  {
    id: "analytics",
    name: "분석",
    description: "커스텀 대시보드 및 AI 질문 결과 저장소",
    color: "bg-violet-500",
    textColor: "text-violet-600",
    icon: "BarChart3",
    createdAt: "2026-01-15",
    itemCount: 3,
    items: [
      {
        id: "builder-main",
        title: "종합 리스크 커스텀 대시보드",
        description: "주요 리스크 지표를 한 화면에 배치한 커스텀 뷰",
        type: "dashboard",
        href: "/dashboards/new",
        createdAt: "2026-02-01",
        updatedAt: "2026-03-05",
        author: "전략기획부",
        pinned: true,
      },
      {
        id: "q-npl-trend",
        title: "NPL 비율 12개월 추이",
        description: "지난 12개월 NPL 비율 추이를 보여줘",
        type: "question",
        href: "/",
        createdAt: "2026-02-10",
        updatedAt: "2026-03-08",
        author: "리스크분석팀",
        pinned: false,
      },
      {
        id: "q-sector-exposure",
        title: "업종별 익스포저 TOP 5",
        description: "업종별 익스포저 TOP 5를 보여줘",
        type: "question",
        href: "/",
        createdAt: "2026-02-15",
        updatedAt: "2026-03-07",
        author: "리스크분석팀",
        pinned: false,
      },
    ],
  },
  {
    id: "my-collection",
    name: "내 컬렉션",
    description: "개인적으로 저장한 대시보드와 질문",
    color: "bg-amber-500",
    textColor: "text-amber-600",
    icon: "Star",
    createdAt: "2026-01-01",
    personal: true,
    itemCount: 2,
    items: [
      {
        id: "my-q-lcr",
        title: "LCR/NSFR 현황 조회",
        description: "현재 LCR과 NSFR 수치를 보여줘",
        type: "question",
        href: "/",
        createdAt: "2026-03-01",
        updatedAt: "2026-03-09",
        author: "나",
        pinned: true,
      },
      {
        id: "my-builder",
        title: "나의 커스텀 대시보드",
        description: "개인 모니터링 대시보드",
        type: "dashboard",
        href: "/dashboards/new",
        createdAt: "2026-03-05",
        updatedAt: "2026-03-10",
        author: "나",
        pinned: false,
      },
    ],
  },
];

export function getCollection(id: string): Collection | undefined {
  return collections.find((c) => c.id === id);
}
